[module]
  path = "github.com/sharmaprateek/hugo-docfind"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "search"
  isPlainText = true
  notAlternative = true

[markup.goldmark.parser]
  attribute = true # Enables {.class #id} syntax
  autoHeadingID = true # Essential for the regex to find IDs
